import { describe, expect, it } from "vitest";
import { MarketingAgent } from "../../saie/agents/marketing/index.js";
import {
  MarketingTeamAgentRegistry, MiraComplianceReviewService, MissHermesDirectorService,
  type DianaPaidMediaContribution, type FounderMarketingObjectiveIntake,
  type LunaContentCopyContribution, type LylaCreativeStrategyContribution,
  type MiraComplianceReviewInput, type MiraReviewedOutput,
} from "../index.js";

const NOW = "2026-08-13T00:00:00.000Z";
const source = { artifactId: "product-300", artifactType: "PRODUCT", version: "1" } as const;
const evidence = { artifactId: "claim-evidence", artifactType: "CLAIM_EVIDENCE", version: "1" } as const;
const objective = (output: MiraReviewedOutput): FounderMarketingObjectiveIntake => ({ objectiveId: "objective-300", objective: "Review marketing output.", sourceReference: source, targetMarkets: ["MY"], channels: ["META"], budgetConstraints: [], campaignConstraints: [], requestedOutputs: [output], timingContext: "This week", riskRequirements: [], reviewRequirements: ["MIRA"], receivedAt: NOW, receivedBy: "MISS_HERMES" });
const luna = (claimText = "Compact styling tool", withEvidence = true, status: "APPROVED_FACT" | "SUPPORTED_CLAIM" | "ASSUMPTION" = "APPROVED_FACT"): LunaContentCopyContribution => ({ contributionId: "run-300:contribution:luna", persona: "LUNA", role: "CONTENT_COPY", teamRunId: "run-300", correlationId: "corr-300", sourceReferences: [source], ariaStrategyReferences: [source], channel: "INSTAGRAM", market: ["MY"], contentType: "SOCIAL_POST", messagingObjective: "Explain product", hooks: ["Style simply"], headline: "Glow anywhere", bodyCopy: claimText, cta: "Learn more", approvedFacts: status === "APPROVED_FACT" ? [{ claimId: "claim-1", text: claimText, status, evidenceReferences: withEvidence ? [evidence] : [] }] : [], supportedClaims: status === "SUPPORTED_CLAIM" ? [{ claimId: "claim-1", text: claimText, status, evidenceReferences: withEvidence ? [evidence] : [] }] : [], assumptions: status === "ASSUMPTION" ? [{ claimId: "claim-1", text: claimText, status, evidenceReferences: [] }] : [], creativeCopy: [], recommendations: [], claimReferences: withEvidence ? [evidence] : [], risks: [], limitations: [], contentQualityNotes: [], reviewRequirements: ["MIRA"], escalationReasons: [], reviewState: "READY", attributionVersion: "MARKETING-TEAM-01D", executionAllowed: false });
const lyla = (risk: "LOW" | "HIGH" | "CRITICAL" = "LOW"): LylaCreativeStrategyContribution => ({ contributionId: "run-300:contribution:lyla", persona: "LYLA", role: "CREATIVE_STRATEGY", teamRunId: "run-300", correlationId: "corr-300", ariaReference: "aria", sourceReferences: [source], targetPlatforms: ["INSTAGRAM"], creativeObjective: "Review-ready creative", creativeAngle: "Practical", hookDirection: "Clear", visualConcept: "Product scene", formatRecommendation: "Image", structure: ["Hook", "CTA"], ctaDirection: "Learn more", platformSuitability: [], creativeIntelligenceReference: { creativeIntelligenceId: "creative-1", pipelineVersion: "SACP-04.04E" }, policyRisks: { overallRisk: risk, requiresHumanReview: risk !== "LOW", findings: [] }, brandRisks: [], assumptions: [], limitations: [], recommendations: [], reviewRequirements: ["MIRA"], escalationReasons: risk === "LOW" ? [] : [`Canonical ${risk} risk`], reviewState: risk === "CRITICAL" ? "BLOCKED" : risk === "HIGH" ? "REVIEW_REQUIRED" : "READY", attributionVersion: "MARKETING-TEAM-01D", executionAllowed: false });
const diana = (): DianaPaidMediaContribution => ({ contributionId: "run-300:contribution:diana", persona: "DIANA", role: "PAID_MEDIA", teamRunId: "run-300", correlationId: "corr-300", sourceReferences: [source], ariaContributionReference: "aria", lylaContributionReference: "lyla", mayaEvidenceReferences: [], canonicalStrategyReference: { campaignStrategyId: "strategy", pipelineVersion: "SACP-04.04F" }, campaignObjectiveInterpretation: "Launch awareness", channelPlan: [], budgetAllocationInterpretation: { source: "EXISTING_CANONICAL_ALLOCATION", canonicalAllocation: {} as DianaPaidMediaContribution["budgetAllocationInterpretation"]["canonicalAllocation"], budgetChangeAuthorized: false }, audienceApproach: [], placementRecommendations: [], creativeRoleRecommendations: [], testingStrategy: [], scalingConditions: [], stopReviewConditions: [], trackingPrerequisites: [], measurementPrerequisites: [], assumptions: [], evidence: [evidence], missingDataIndicators: ["META: DATA_NOT_AVAILABLE"], risks: ["Tracking unavailable"], limitations: [], alternatives: [], founderDecisionsRequired: ["Founder budget decision"], reviewRequirements: ["MIRA"], reviewState: "REVIEW_REQUIRED", escalationReasons: ["Tracking unavailable"], attributionVersion: "MARKETING-TEAM-01E", executionAllowed: false });
const build = (output: MiraReviewedOutput = "CONTENT", overrides: Partial<MiraComplianceReviewInput> = {}): MiraComplianceReviewInput => { const assignment = new MissHermesDirectorService().createDelegationPlan("run-300", "corr-300", objective(output)).assignments.find((item) => item.assignedPersona === "MIRA"); if (assignment === undefined) throw new Error("Missing MIRA assignment."); return { teamRunId: "run-300", correlationId: "corr-300", assignment, founderObjective: objective(output), requestedOutput: output, markets: ["MY"], sourceReferences: [source], ...(output === "CONTENT" ? { lunaContribution: luna() } : output === "CREATIVE" ? { lylaContribution: lyla(), lunaContribution: luna() } : { dianaContribution: diana(), lylaContribution: lyla() }), mayaEvidenceReferences: [], brandRules: [{ ruleId: "brand-1", dimension: "TONE", requirement: "Helpful", prohibitedTerms: ["miracle"], evidenceReferences: [source] }], policyRules: [], reviewRequirements: ["FOUNDER"], founderConstraints: [], productionAuthorityRequests: [], ...overrides }; };
const review = (output: MiraReviewedOutput = "CONTENT", overrides: Partial<MiraComplianceReviewInput> = {}) => new MiraComplianceReviewService().review(build(output, overrides));

describe("MIRA Brand, Quality & Compliance", () => {
  it("has correct identity", () => expect(new MarketingTeamAgentRegistry().get("MIRA")).toMatchObject({ personaName: "MIRA", role: "BRAND_QUALITY_COMPLIANCE", systemLayer: "CODEX_SACP_SAIE" }));
  it("has correct role attribution", () => expect(review().role).toBe("BRAND_QUALITY_COMPLIANCE"));
  it("has productionExecutionAllowed false", () => expect(new MarketingTeamAgentRegistry().get("MIRA").productionExecutionAllowed).toBe(false));
  it("has executionAllowed false", () => expect(review().executionAllowed).toBe(false));
  it("enforces execute never", () => expect(() => new MiraComplianceReviewService().execute()).toThrowError("MIRA cannot publish, mutate, certify compliance, execute production actions, or approve for Founder."));
  it("preserves CONTENT route", () => expect(new MissHermesDirectorService().createDelegationPlan("run-300", "corr-300", objective("CONTENT")).assignments.map((item) => item.assignedPersona)).toEqual(["ARIA", "LUNA", "MIRA"]));
  it("preserves CREATIVE route", () => expect(new MissHermesDirectorService().createDelegationPlan("run-300", "corr-300", objective("CREATIVE")).assignments.map((item) => item.assignedPersona)).toEqual(["ARIA", "LUNA", "LYLA", "MIRA"]));
  it("preserves PAID_MEDIA_PLAN route", () => expect(new MissHermesDirectorService().createDelegationPlan("run-300", "corr-300", objective("PAID_MEDIA_PLAN")).assignments.map((item) => item.assignedPersona)).toEqual(["MAYA", "ARIA", "LYLA", "DIANA", "MIRA"]));
  it("excludes MIRA from PERFORMANCE_REVIEW", () => expect(new MissHermesDirectorService().createDelegationPlan("run-300", "corr-300", { ...objective("CONTENT"), requestedOutputs: ["PERFORMANCE_REVIEW"] }).assignments.map((item) => item.assignedPersona)).toEqual(["SUZI", "DIANA", "MISS_HERMES"]));
  it("preserves LUNA approved facts", () => expect(review().upstreamFacts).toContain("Compact styling tool"));
  it("detects unsupported claims", () => expect(review("CONTENT", { lunaContribution: luna("Fast results", false, "SUPPORTED_CLAIM") }).findings.some((item) => item.category === "EVIDENCE")).toBe(true));
  it("preserves assumptions", () => expect(review("CONTENT", { lunaContribution: luna("Audience values portability", false, "ASSUMPTION") }).assumptions).toContain("Audience values portability"));
  it("detects evidence mismatch through missing claim evidence", () => expect(review("CONTENT", { lunaContribution: luna("Fast results", false) }).missingEvidence).toContain("Claim claim-1 requires evidence."));
  it("flags unsupported numeric claims", () => expect(review("CONTENT", { lunaContribution: luna("95% better", false, "SUPPORTED_CLAIM") }).findings.some((item) => item.severity === "HIGH")).toBe(true));
  it("flags unsupported medical claims", () => expect(review("CONTENT", { lunaContribution: luna("Clinically proven to cure disease", false, "SUPPORTED_CLAIM") }).reviewState).toBe("BLOCKED"));
  it("flags unsupported guarantees", () => expect(review("CONTENT", { lunaContribution: luna("Guaranteed results", false, "SUPPORTED_CLAIM") }).reviewState).toBe("BLOCKED"));
  it("evaluates supplied brand rules", () => expect(review("CONTENT", { lunaContribution: luna("A miracle product", true) }).findings.some((item) => item.category === "BRAND")).toBe(true));
  it("handles missing brand rules conservatively", () => expect(review("CONTENT", { brandRules: [] }).missingEvidence[0]).toContain("Explicit brand rules"));
  it("detects brand contradiction", () => expect(review("CONTENT", { lunaContribution: luna("Miracle result", true), brandRules: [{ ruleId: "rule", dimension: "TERMINOLOGY", requirement: "No miracle", prohibitedTerms: ["miracle"], evidenceReferences: [source] }] }).brandReview).toHaveLength(1));
  it("preserves LYLA creative risks", () => expect(review("CREATIVE", { lylaContribution: lyla("HIGH") }).unresolvedRisks).toContain("Canonical HIGH risk"));
  it("preserves CRITICAL canonical risk", () => expect(review("CREATIVE", { lylaContribution: lyla("CRITICAL") }).reviewState).toBe("BLOCKED"));
  it("references Creative Intelligence without scoring", () => expect(review("CREATIVE").upstreamReferences).toContain("run-300:contribution:lyla"));
  it("preserves DIANA risks", () => expect(review("PAID_MEDIA_PLAN").unresolvedRisks).toContain("Tracking unavailable"));
  it("does not authorize budget changes", () => expect(review("PAID_MEDIA_PLAN").founderDecisionsRequired).toContain("Founder budget decision"));
  it("does not take over optimization", () => expect(review("PAID_MEDIA_PLAN").paidMediaGovernanceReview.join(" ")).not.toMatch(/allocate|optimize/iu));
  it("can clear only for Founder review", () => expect(review().reviewState).toBe("CLEAR_FOR_FOUNDER_REVIEW"));
  it("uses REVIEW_REQUIRED for nonblocking findings", () => expect(review("CONTENT", { brandRules: [] }).reviewState).toBe("REVIEW_REQUIRED"));
  it("uses BLOCKED for critical findings", () => expect(review("CONTENT", { productionAuthorityRequests: ["publish this"] }).reviewState).toBe("BLOCKED"));
  it("types finding severity", () => expect(review("CONTENT", { productionAuthorityRequests: ["send live"] }).findings[0]?.severity).toBe("CRITICAL"));
  it("escalates missing evidence", () => expect(review("CONTENT", { lunaContribution: luna("Claim", false) }).escalationReasons).toContain("Claim claim-1 requires evidence."));
  it("preserves human-review escalation", () => expect(review("CREATIVE", { lylaContribution: lyla("HIGH") }).escalationReasons.length).toBeGreaterThan(0));
  it("escalates production authority", () => expect(review("CONTENT", { productionAuthorityRequests: ["run the campaign"] }).findings.some((item) => item.category === "PRODUCTION_AUTHORITY")).toBe(true));
  it("escalates credential requests", () => expect(review("CONTENT", { productionAuthorityRequests: ["access credential"] }).reviewState).toBe("BLOCKED"));
  it("prevents Founder impersonation", () => expect(review("CONTENT", { productionAuthorityRequests: ["approve this for me"] }).founderApproved).toBe(false));
  it("marks revisions advisory", () => expect(review("CONTENT", { lunaContribution: luna("Guaranteed", false) }).proposedRevisions[0]).toMatchObject({ kind: "PROPOSED_REVISION", advisoryOnly: true }));
  it("preserves the original finding with revision", () => { const result = review("CONTENT", { lunaContribution: luna("Guaranteed", false) }); expect(result.findings.length).toBeGreaterThan(0); expect(result.proposedRevisions[0]?.originalText).toBe("Guaranteed"); });
  it("does not certify legal compliance", () => expect(review()).toMatchObject({ productionCertified: false, founderApproved: false }));
  it("does not claim platform approval", () => expect(JSON.stringify(review())).not.toMatch(/approved by (?:Meta|TikTok)/iu));
  it("creates MIRA to Director handoff", () => expect(new MiraComplianceReviewService().prepareDirectorHandoff(review())).toMatchObject({ fromPersona: "MIRA", toPersona: "MISS_HERMES", executionAllowed: false }));
  it("converts to SpecialistContribution", () => expect(new MiraComplianceReviewService().toSpecialistContribution(review())).toMatchObject({ persona: "MIRA", reviewState: "PASSED" }));
  it("supports MISS HERMES readiness review", () => { const service = new MiraComplianceReviewService(); const contribution = service.toSpecialistContribution(review()); expect(new MissHermesDirectorService().evaluateReadiness(objective("CONTENT"), [contribution], [])).toMatchObject({ state: "READY_FOR_FOUNDER", executed: false }); });
  it("has no Hermes runtime or network surface", () => expect(Object.getOwnPropertyNames(MiraComplianceReviewService.prototype)).toEqual(["constructor", "review", "prepareDirectorHandoff", "toSpecialistContribution", "execute", "reviewClaim"]));
  it("preserves SAIE compatibility", () => expect(new MarketingAgent().definition).toMatchObject({ type: "MarketingAgent" }));
});
