import type { LunaClaimInput } from "../domain/luna-lyla-specialist.model.js";
import type { MiraComplianceReviewContribution, MiraComplianceReviewInput, MiraDirectorReviewHandoff, MiraFindingCategory, MiraFindingSeverity, MiraProposedRevision, MiraReviewFinding } from "../domain/mira-compliance-review.model.js";
import { MIRA_REVIEW_VERSION, MiraComplianceReviewError } from "../domain/mira-compliance-review.model.js";
import type { SpecialistContribution } from "../domain/miss-hermes-director.model.js";
import type { MarketingArtifactReference } from "../domain/marketing-team.model.js";
import { MarketingTeamAgentRegistry } from "../domain/marketing-team.registry.js";

const SENSITIVE = /cure|treats? disease|prevents? disease|medically proven|clinically proven|dermatologist approved|guaranteed|\b\d+(?:\.\d+)?%|best|superior|limited time|only \d+ left/iu;
const PRODUCTION = /publish|send live|run (?:the )?campaign|change (?:the )?budget|change targeting|credential|schedule|approve (?:this )?for me|founder approval/iu;
export class MiraComplianceReviewService {
  public constructor(registry = new MarketingTeamAgentRegistry()) { const mira = registry.get("MIRA"); if (mira.role !== "BRAND_QUALITY_COMPLIANCE" || mira.systemLayer !== "CODEX_SACP_SAIE" || mira.productionExecutionAllowed !== false) throw new MiraComplianceReviewError("MIRA_IDENTITY_INVALID", "MIRA governance identity is invalid."); }
  public review(input: MiraComplianceReviewInput): MiraComplianceReviewContribution {
    required(input.teamRunId, "teamRunId"); required(input.correlationId, "correlationId");
    if (input.assignment.assignedPersona !== "MIRA") throw new MiraComplianceReviewError("MIRA_ASSIGNMENT_INVALID", "MIRA requires a MIRA assignment.");
    const expected = input.requestedOutput === "CONTENT" ? "luna" : input.requestedOutput === "CREATIVE" ? "lyla" : "diana";
    if (!input.assignment.dependencies.includes(`${input.teamRunId}:assignment:${expected}`)) throw new MiraComplianceReviewError("MIRA_DEPENDENCY_INVALID", `MIRA requires direct ${expected.toUpperCase()} dependency for ${input.requestedOutput}.`);
    if (input.requestedOutput === "CONTENT" && input.lunaContribution === undefined) throw new MiraComplianceReviewError("LUNA_CONTRIBUTION_REQUIRED", "CONTENT review requires LUNA contribution.");
    if (input.requestedOutput === "CREATIVE" && input.lylaContribution === undefined) throw new MiraComplianceReviewError("LYLA_CONTRIBUTION_REQUIRED", "CREATIVE review requires LYLA contribution.");
    if (input.requestedOutput === "PAID_MEDIA_PLAN" && input.dianaContribution === undefined) throw new MiraComplianceReviewError("DIANA_CONTRIBUTION_REQUIRED", "PAID_MEDIA_PLAN review requires DIANA contribution.");
    for (const value of [input.ariaContribution, input.lunaContribution, input.lylaContribution, input.dianaContribution]) if (value !== undefined && (value.teamRunId !== input.teamRunId || value.correlationId !== input.correlationId)) throw new MiraComplianceReviewError("UPSTREAM_CORRELATION_INVALID", "Upstream contributions must preserve run and correlation identity.");
    const findings: MiraReviewFinding[] = []; const missingEvidence: string[] = []; const proposedRevisions: MiraProposedRevision[] = [];
    const add = (category: MiraFindingCategory, severity: MiraFindingSeverity, persona: MiraReviewFinding["affectedPersona"], sourceReference: string, evidenceBasis: readonly MarketingArtifactReference[], explanation: string, correction: string, founder = severity === "HIGH" || severity === "CRITICAL") => findings.push({ findingId: `${input.teamRunId}:finding:${findings.length + 1}`, category, severity, affectedPersona: persona, sourceReference, evidenceBasis: evidenceBasis.map((item) => ({ ...item })), explanation, recommendedCorrection: correction, founderDecisionRequired: founder });
    const claims = input.lunaContribution === undefined ? [] : [...input.lunaContribution.approvedFacts, ...input.lunaContribution.supportedClaims, ...input.lunaContribution.assumptions];
    for (const claim of claims) this.reviewClaim(claim, add, missingEvidence, proposedRevisions);
    if (input.brandRules.length === 0) missingEvidence.push("Explicit brand rules were not supplied; only conservative consistency review was performed.");
    const reviewedText = [input.lunaContribution?.headline, input.lunaContribution?.bodyCopy, input.lunaContribution?.cta, input.lylaContribution?.creativeObjective, input.dianaContribution?.campaignObjectiveInterpretation].filter((item): item is string => item !== undefined).join(" ");
    for (const rule of input.brandRules) for (const term of rule.prohibitedTerms) if (reviewedText.toLowerCase().includes(term.toLowerCase())) add("BRAND", "MEDIUM", input.requestedOutput === "CONTENT" ? "LUNA" : input.requestedOutput === "CREATIVE" ? "LYLA" : "DIANA", rule.ruleId, rule.evidenceReferences, `Supplied brand rule conflicts with term: ${term}.`, "Align terminology with the supplied brand rule.", true);
    for (const rule of input.policyRules) for (const term of rule.prohibitedTerms) if (reviewedText.toLowerCase().includes(term.toLowerCase())) add("CREATIVE_POLICY", "HIGH", input.requestedOutput === "CONTENT" ? "LUNA" : input.requestedOutput === "CREATIVE" ? "LYLA" : "DIANA", rule.ruleId, rule.evidenceReferences, `Supplied policy rule flags term: ${term}.`, "Request governed policy review and revision.");
    if (input.lylaContribution !== undefined) { if (["HIGH", "CRITICAL"].includes(input.lylaContribution.policyRisks.overallRisk)) add("CREATIVE_POLICY", input.lylaContribution.policyRisks.overallRisk, "LYLA", input.lylaContribution.contributionId, input.lylaContribution.sourceReferences, "Canonical Creative Intelligence retains high or critical policy risk.", "Return creative for review; do not publish."); for (const risk of input.lylaContribution.escalationReasons) add("CREATIVE_POLICY", "MEDIUM", "LYLA", input.lylaContribution.contributionId, input.lylaContribution.sourceReferences, risk, "Resolve the preserved upstream review requirement."); }
    if (input.dianaContribution !== undefined) { for (const risk of input.dianaContribution.risks) add("PAID_MEDIA_POLICY", "MEDIUM", "DIANA", input.dianaContribution.contributionId, input.dianaContribution.evidence, risk, "Resolve the paid-media risk without changing allocation or spend."); if (input.dianaContribution.founderDecisionsRequired.length > 0) add("GOVERNANCE", "HIGH", "DIANA", input.dianaContribution.contributionId, input.dianaContribution.evidence, "DIANA retains Founder budget or authority decisions.", "Present the decisions to Founder; MIRA cannot authorize spend."); }
    for (const request of [...input.productionAuthorityRequests, ...input.founderConstraints]) if (PRODUCTION.test(request)) add("PRODUCTION_AUTHORITY", "CRITICAL", input.requestedOutput === "CONTENT" ? "LUNA" : input.requestedOutput === "CREATIVE" ? "LYLA" : "DIANA", "FOUNDER_CONSTRAINT", [], `Production or Founder authority request detected: ${request}`, "Escalate to Founder; no action may be executed.");
    const upstreamRisks = [...(input.lunaContribution?.risks ?? []), ...(input.lylaContribution?.escalationReasons ?? []), ...(input.dianaContribution?.risks ?? [])];
    const evidenceReferences = dedupe([...input.sourceReferences, ...input.mayaEvidenceReferences, ...claims.flatMap((claim) => claim.evidenceReferences), ...findings.flatMap((finding) => finding.evidenceBasis)]);
    const escalationReasons = findings.filter((item) => item.severity === "HIGH" || item.severity === "CRITICAL" || item.founderDecisionRequired).map((item) => item.explanation);
    if (missingEvidence.length > 0) escalationReasons.push(...missingEvidence);
    const blocked = findings.some((item) => item.severity === "CRITICAL") || claims.some((claim) => claim.status !== "ASSUMPTION" && claim.evidenceReferences.length === 0 && SENSITIVE.test(claim.text));
    return { contributionId: `${input.teamRunId}:contribution:mira`, persona: "MIRA", role: "BRAND_QUALITY_COMPLIANCE", teamRunId: input.teamRunId, correlationId: input.correlationId, reviewedOutput: input.requestedOutput,
      upstreamReferences: [input.ariaContribution?.contributionId, input.lunaContribution?.contributionId, input.lylaContribution?.contributionId, input.dianaContribution?.contributionId].filter((item): item is string => item !== undefined), evidenceReferences,
      upstreamFacts: claims.filter((claim) => claim.status === "APPROVED_FACT").map((claim) => claim.text), brandReview: findings.filter((item) => item.category === "BRAND").map((item) => item.explanation), claimReview: findings.filter((item) => item.category === "CLAIM" || item.category === "EVIDENCE").map((item) => item.explanation), contentQualityReview: findings.filter((item) => item.category === "CONTENT_QUALITY").map((item) => item.explanation), creativePolicyReview: findings.filter((item) => item.category === "CREATIVE_POLICY").map((item) => item.explanation), paidMediaGovernanceReview: findings.filter((item) => item.category === "PAID_MEDIA_POLICY" || item.category === "TRACKING").map((item) => item.explanation), findings,
      unresolvedRisks: [...new Set([...upstreamRisks, ...findings.map((item) => item.explanation)])], missingEvidence, assumptions: claims.filter((claim) => claim.status === "ASSUMPTION").map((claim) => claim.text), limitations: ["Review is limited to supplied rules, evidence, and canonical upstream intelligence.", "MIRA provides no legal certification or platform approval."], proposedRevisions, founderDecisionsRequired: [...new Set([...findings.filter((item) => item.founderDecisionRequired).map((item) => item.explanation), ...(input.dianaContribution?.founderDecisionsRequired ?? [])])], escalationReasons: [...new Set(escalationReasons)], reviewState: blocked ? "BLOCKED" : findings.length > 0 || missingEvidence.length > 0 ? "REVIEW_REQUIRED" : "CLEAR_FOR_FOUNDER_REVIEW", reviewRequirements: [...input.reviewRequirements], attributionVersion: MIRA_REVIEW_VERSION, founderApproved: false, productionCertified: false, executionAllowed: false };
  }
  public prepareDirectorHandoff(value: MiraComplianceReviewContribution): MiraDirectorReviewHandoff { return { handoffId: `${value.teamRunId}:handoff:mira-director`, teamRunId: value.teamRunId, correlationId: value.correlationId, miraContribution: structuredClone(value), upstreamSpecialistReferences: [...value.upstreamReferences], findings: structuredClone(value.findings), evidenceReferences: value.evidenceReferences.map((item) => ({ ...item })), unresolvedRisks: [...value.unresolvedRisks], requiredRevisions: structuredClone(value.proposedRevisions), founderDecisionsRequired: [...value.founderDecisionsRequired], reviewState: value.reviewState, fromPersona: "MIRA", toPersona: "MISS_HERMES", executionAllowed: false }; }
  public toSpecialistContribution(value: MiraComplianceReviewContribution): SpecialistContribution { return { contributionId: value.contributionId, persona: "MIRA", summary: `${value.reviewedOutput} review: ${value.reviewState}.`, recommendation: value.reviewState === "CLEAR_FOR_FOUNDER_REVIEW" ? "Proceed to Founder review; no production approval is implied." : "Resolve findings before Founder production consideration.", assumptions: [...value.assumptions], risks: [...value.unresolvedRisks], confidence: value.reviewState === "CLEAR_FOR_FOUNDER_REVIEW" ? "HIGH" : value.reviewState === "BLOCKED" ? "LOW" : "MEDIUM", evidence: value.evidenceReferences.map((item) => ({ ...item })), dependencies: value.evidenceReferences.map((item) => ({ ...item })), reviewState: value.reviewState === "CLEAR_FOR_FOUNDER_REVIEW" ? "PASSED" : value.reviewState === "BLOCKED" ? "BLOCKED" : "PENDING" }; }
  public execute(): never { throw new MiraComplianceReviewError("PRODUCTION_EXECUTION_PROHIBITED", "MIRA cannot publish, mutate, certify compliance, execute production actions, or approve for Founder."); }
  private reviewClaim(claim: LunaClaimInput, add: (category: MiraFindingCategory, severity: MiraFindingSeverity, persona: "LUNA", source: string, evidence: readonly MarketingArtifactReference[], explanation: string, correction: string, founder?: boolean) => void, missingEvidence: string[], revisions: { kind: "PROPOSED_REVISION"; findingId: string; originalText: string; proposedText: string; advisoryOnly: true }[]): void { if (claim.status === "ASSUMPTION") return; const unsupported = claim.evidenceReferences.length === 0; const sensitive = SENSITIVE.test(claim.text); if (!unsupported && !sensitive) return; const id = `${claim.claimId}`; const explanation = unsupported ? `Claim ${claim.claimId} lacks governed supporting evidence.` : `Claim ${claim.claimId} uses sensitive certainty requiring human review.`; add(unsupported ? "EVIDENCE" : "CLAIM", sensitive ? "HIGH" : "MEDIUM", "LUNA", id, claim.evidenceReferences, explanation, "Request evidence or soften unsupported certainty.", sensitive); revisions.push({ kind: "PROPOSED_REVISION", findingId: id, originalText: claim.text, proposedText: "Use qualified wording supported by supplied evidence.", advisoryOnly: true }); if (unsupported) missingEvidence.push(`Claim ${claim.claimId} requires evidence.`); }
}
function required(value: string, field: string): void { if (value.trim().length === 0) throw new MiraComplianceReviewError("REQUIRED_FIELD_MISSING", `${field} is required.`); }
function dedupe(values: readonly MarketingArtifactReference[]): readonly MarketingArtifactReference[] { return [...new Map(values.map((item) => [`${item.artifactType}:${item.artifactId}:${item.version}`, item])).values()].map((item) => ({ ...item })); }
