import type { DianaPaidMediaContribution } from "./diana-paid-media.model.js";
import type { LunaContentCopyContribution, LylaCreativeStrategyContribution } from "./luna-lyla-specialist.model.js";
import type { AriaCampaignStrategyContribution } from "./maya-aria-specialist.model.js";
import type { FounderMarketingObjectiveIntake, SpecialistAssignment, SpecialistContribution } from "./miss-hermes-director.model.js";
import type { MarketingArtifactReference, MarketingTeamReviewRequirement } from "./marketing-team.model.js";

export const MIRA_REVIEW_VERSION = "MARKETING-TEAM-01G";
export type MiraReviewedOutput = "CONTENT" | "CREATIVE" | "PAID_MEDIA_PLAN";
export type MiraReviewState = "CLEAR_FOR_FOUNDER_REVIEW" | "REVIEW_REQUIRED" | "BLOCKED";
export type MiraFindingCategory = "BRAND" | "CLAIM" | "CONTENT_QUALITY" | "CREATIVE_POLICY" | "PAID_MEDIA_POLICY" | "EVIDENCE" | "TRACKING" | "GOVERNANCE" | "PRODUCTION_AUTHORITY";
export type MiraFindingSeverity = "INFO" | "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export interface MiraBrandRule { readonly ruleId: string; readonly dimension: "VOICE" | "POSITIONING" | "TONE" | "TERMINOLOGY" | "PRODUCT_NAME" | "MARKET_MESSAGE" | "CTA"; readonly requirement: string; readonly prohibitedTerms: readonly string[]; readonly evidenceReferences: readonly MarketingArtifactReference[]; }
export interface MiraPolicyRule { readonly ruleId: string; readonly description: string; readonly prohibitedTerms: readonly string[]; readonly evidenceReferences: readonly MarketingArtifactReference[]; }
export interface MiraReviewFinding { readonly findingId: string; readonly category: MiraFindingCategory; readonly severity: MiraFindingSeverity; readonly affectedPersona: "LUNA" | "LYLA" | "DIANA" | "ARIA"; readonly sourceReference: string; readonly evidenceBasis: readonly MarketingArtifactReference[]; readonly explanation: string; readonly recommendedCorrection: string; readonly founderDecisionRequired: boolean; }
export interface MiraProposedRevision { readonly kind: "PROPOSED_REVISION"; readonly findingId: string; readonly originalText: string; readonly proposedText: string; readonly advisoryOnly: true; }
export interface MiraComplianceReviewInput { readonly teamRunId: string; readonly correlationId: string; readonly assignment: SpecialistAssignment; readonly founderObjective: FounderMarketingObjectiveIntake; readonly requestedOutput: MiraReviewedOutput; readonly markets: readonly string[]; readonly sourceReferences: readonly MarketingArtifactReference[]; readonly ariaContribution?: AriaCampaignStrategyContribution; readonly lunaContribution?: LunaContentCopyContribution; readonly lylaContribution?: LylaCreativeStrategyContribution; readonly dianaContribution?: DianaPaidMediaContribution; readonly mayaEvidenceReferences: readonly MarketingArtifactReference[]; readonly brandRules: readonly MiraBrandRule[]; readonly policyRules: readonly MiraPolicyRule[]; readonly reviewRequirements: readonly MarketingTeamReviewRequirement[]; readonly founderConstraints: readonly string[]; readonly productionAuthorityRequests: readonly string[]; }
export interface MiraComplianceReviewContribution { readonly contributionId: string; readonly persona: "MIRA"; readonly role: "BRAND_QUALITY_COMPLIANCE"; readonly teamRunId: string; readonly correlationId: string; readonly reviewedOutput: MiraReviewedOutput; readonly upstreamReferences: readonly string[]; readonly evidenceReferences: readonly MarketingArtifactReference[]; readonly upstreamFacts: readonly string[]; readonly brandReview: readonly string[]; readonly claimReview: readonly string[]; readonly contentQualityReview: readonly string[]; readonly creativePolicyReview: readonly string[]; readonly paidMediaGovernanceReview: readonly string[]; readonly findings: readonly MiraReviewFinding[]; readonly unresolvedRisks: readonly string[]; readonly missingEvidence: readonly string[]; readonly assumptions: readonly string[]; readonly limitations: readonly string[]; readonly proposedRevisions: readonly MiraProposedRevision[]; readonly founderDecisionsRequired: readonly string[]; readonly escalationReasons: readonly string[]; readonly reviewState: MiraReviewState; readonly reviewRequirements: readonly MarketingTeamReviewRequirement[]; readonly attributionVersion: typeof MIRA_REVIEW_VERSION; readonly founderApproved: false; readonly productionCertified: false; readonly executionAllowed: false; }
export interface MiraDirectorReviewHandoff { readonly handoffId: string; readonly teamRunId: string; readonly correlationId: string; readonly miraContribution: MiraComplianceReviewContribution; readonly upstreamSpecialistReferences: readonly string[]; readonly findings: readonly MiraReviewFinding[]; readonly evidenceReferences: readonly MarketingArtifactReference[]; readonly unresolvedRisks: readonly string[]; readonly requiredRevisions: readonly MiraProposedRevision[]; readonly founderDecisionsRequired: readonly string[]; readonly reviewState: MiraReviewState; readonly fromPersona: "MIRA"; readonly toPersona: "MISS_HERMES"; readonly executionAllowed: false; }
export interface MiraContributionAdapter { readonly mira: SpecialistContribution; }
export class MiraComplianceReviewError extends Error { public constructor(public readonly code: string, message: string) { super(message); this.name = "MiraComplianceReviewError"; } }
