import type { ProductMediaAssetType, ProductMediaBrandProfile, ProductMediaSpecification } from "../../domain/models/index.js";

export const PRODUCT_MEDIA_DEFAULT_SPECIFICATIONS: Readonly<Record<ProductMediaAssetType, Omit<ProductMediaSpecification, "locale" | "sourceAssetIds">>> = {
  PRODUCT_HERO: {
    assetType: "PRODUCT_HERO",
    purpose: "Primary Shopify product media",
    aspectRatio: "1:1",
    width: 2048,
    height: 2048,
    format: "png",
    backgroundRequirement: "clean premium background",
    textOverlayPolicy: "none",
    safeAreaGuidance: "center product with generous edge spacing",
    productPlacementGuidance: "product centered and clearly visible",
    targetChannel: "shopify-product",
    variantCount: 1,
    qualityLevel: "premium",
  },
  PRODUCT_GALLERY: {
    assetType: "PRODUCT_GALLERY",
    purpose: "Supporting Shopify product gallery media",
    aspectRatio: "1:1",
    width: 2048,
    height: 2048,
    format: "png",
    backgroundRequirement: "consistent product-focused background",
    textOverlayPolicy: "none",
    safeAreaGuidance: "keep product fully inside frame",
    productPlacementGuidance: "alternate angle without changing product identity",
    targetChannel: "shopify-product",
    variantCount: 1,
    qualityLevel: "premium",
  },
  LIFESTYLE: {
    assetType: "LIFESTYLE",
    purpose: "Lifestyle context for product storytelling",
    aspectRatio: "4:5",
    width: 1200,
    height: 1500,
    format: "jpg",
    backgroundRequirement: "brand-appropriate lifestyle scene",
    textOverlayPolicy: "none",
    safeAreaGuidance: "avoid cropping the product",
    productPlacementGuidance: "product present in realistic context",
    targetChannel: "storefront",
    variantCount: 1,
    qualityLevel: "premium",
  },
  BENEFIT_CARD: {
    assetType: "BENEFIT_CARD",
    purpose: "Visual support for verified benefits",
    aspectRatio: "1:1",
    width: 1080,
    height: 1080,
    format: "png",
    backgroundRequirement: "simple editorial background",
    textOverlayPolicy: "minimal",
    safeAreaGuidance: "reserve center-safe composition",
    productPlacementGuidance: "benefit visual must not imply clinical proof",
    targetChannel: "storefront",
    variantCount: 1,
    qualityLevel: "standard",
  },
  INGREDIENT_CARD: {
    assetType: "INGREDIENT_CARD",
    purpose: "Verified ingredient education",
    aspectRatio: "1:1",
    width: 1080,
    height: 1080,
    format: "png",
    backgroundRequirement: "clean ingredient-focused composition",
    textOverlayPolicy: "minimal",
    safeAreaGuidance: "leave safe area for future labels",
    productPlacementGuidance: "ingredient visuals only when verified",
    targetChannel: "storefront",
    variantCount: 1,
    qualityLevel: "standard",
  },
  HOW_TO_USE: {
    assetType: "HOW_TO_USE",
    purpose: "Usage instruction visual",
    aspectRatio: "1:1",
    width: 1080,
    height: 1080,
    format: "png",
    backgroundRequirement: "clear instructional composition",
    textOverlayPolicy: "minimal",
    safeAreaGuidance: "keep steps readable for future overlays",
    productPlacementGuidance: "show only verified usage steps",
    targetChannel: "storefront",
    variantCount: 1,
    qualityLevel: "standard",
  },
  FEATURE_HIGHLIGHT: {
    assetType: "FEATURE_HIGHLIGHT",
    purpose: "Single verified feature highlight",
    aspectRatio: "1:1",
    width: 1080,
    height: 1080,
    format: "png",
    backgroundRequirement: "premium editorial background",
    textOverlayPolicy: "minimal",
    safeAreaGuidance: "focus on one feature",
    productPlacementGuidance: "do not exaggerate product size",
    targetChannel: "storefront",
    variantCount: 1,
    qualityLevel: "standard",
  },
  COLLECTION_TILE: {
    assetType: "COLLECTION_TILE",
    purpose: "Collection and homepage card media",
    aspectRatio: "4:5",
    width: 1200,
    height: 1500,
    format: "jpg",
    backgroundRequirement: "collection-friendly premium background",
    textOverlayPolicy: "none",
    safeAreaGuidance: "subject visible in card crop",
    productPlacementGuidance: "product/category context clear",
    targetChannel: "collection",
    variantCount: 1,
    qualityLevel: "premium",
  },
  SOCIAL_SQUARE: {
    assetType: "SOCIAL_SQUARE",
    purpose: "1:1 social creative",
    aspectRatio: "1:1",
    width: 1080,
    height: 1080,
    format: "jpg",
    backgroundRequirement: "social-ready premium background",
    textOverlayPolicy: "minimal",
    safeAreaGuidance: "keep product and future text in safe center",
    productPlacementGuidance: "product identity preserved",
    targetChannel: "social",
    variantCount: 1,
    qualityLevel: "standard",
  },
  SOCIAL_VERTICAL: {
    assetType: "SOCIAL_VERTICAL",
    purpose: "9:16 short-form social creative",
    aspectRatio: "9:16",
    width: 1080,
    height: 1920,
    format: "jpg",
    backgroundRequirement: "vertical storytelling scene",
    textOverlayPolicy: "minimal",
    safeAreaGuidance: "avoid top and bottom UI obstruction zones",
    productPlacementGuidance: "product visible in vertical frame",
    targetChannel: "social",
    variantCount: 1,
    qualityLevel: "standard",
  },
  AD_CREATIVE: {
    assetType: "AD_CREATIVE",
    purpose: "Future advertising creative record",
    aspectRatio: "1:1",
    width: 1080,
    height: 1080,
    format: "jpg",
    backgroundRequirement: "conversion-focused premium background",
    textOverlayPolicy: "minimal",
    safeAreaGuidance: "avoid excessive claims or crowded composition",
    productPlacementGuidance: "truthful product quantity and size",
    targetChannel: "ads",
    variantCount: 1,
    qualityLevel: "standard",
  },
  THUMBNAIL: {
    assetType: "THUMBNAIL",
    purpose: "Compact product thumbnail",
    aspectRatio: "1:1",
    width: 512,
    height: 512,
    format: "webp",
    backgroundRequirement: "simple product-first background",
    textOverlayPolicy: "none",
    safeAreaGuidance: "product remains legible at small size",
    productPlacementGuidance: "clear product silhouette",
    targetChannel: "thumbnail",
    variantCount: 1,
    qualityLevel: "standard",
  },
};

export const DEFAULT_PRODUCT_MEDIA_ASSET_TYPES: readonly ProductMediaAssetType[] = [
  "PRODUCT_HERO",
  "PRODUCT_GALLERY",
  "LIFESTYLE",
  "BENEFIT_CARD",
  "FEATURE_HIGHLIGHT",
  "COLLECTION_TILE",
  "SOCIAL_SQUARE",
  "SOCIAL_VERTICAL",
  "AD_CREATIVE",
  "THUMBNAIL",
];

export const DEFAULT_BRAND_MEDIA_PROFILE: ProductMediaBrandProfile = {
  brandName: "Generic Commerce Brand",
  visualIdentity: ["clean", "premium"],
  preferredColorPalette: ["white", "neutral"],
  mood: ["trustworthy", "polished"],
  lightingDirection: "soft commercial lighting",
  backgroundPreferences: ["clean neutral backgrounds"],
  typographyGuidance: "minimal future overlays only",
  prohibitedStyles: ["medical before-after", "third-party logos", "unverified badges"],
  targetAudience: ["commerce shoppers"],
  locale: "en-US",
  channelPreferences: ["shopify-product", "storefront", "social"],
};
